### PR TITLE
Update battery image to include SMBus labels and some descriptive text

### PR DESCRIPTION
**Pull request by hamishwillee**
This addresses last part of #258 by adding SMBus labels and some text. INformation is relevant to, and hence added to both, battery charger and bay topics.

[Review on Reviewable](https://reviewable.io/reviews/3drobotics/solodevguide/275)

### CODE REVIEW

**Comment by OXINARF** [comment]
Bah once again an internal link is failing the tests. I'll try to find a workaround.

And by the way you may want to remove the leading slash from the images links so that they here in GitHub (like you have done before).

**Comment by hamishwillee** [comment]
@OXINARF Thanks very much I fixed the leading slash. The figure link works on local build for me ...

**Comment by OXINARF** [comment]
@hamishwillee Yeah, I figured it would be working for you. One of issues with tests/production is that tests are downloading the latest versions of same plugins, while I'm sure production has fixed versions. Is there anyway you guys can post what versions there are at production?

The plugin for the images has been updated just 3 days ago so there can be a change in id generation... I'm trying to check.

**Comment by OXINARF** [comment]
So I checked the plugin but the issue doesn't seem to be there. Since there is generation of ids it seems it has always been done the same way.
The issue with this one seems to be with the crawler, I'll try to check tomorrow if something can be done about it.

**Comment by OXINARF** [comment]
After a long search and a lot of testing I have the conclusions:

- this one is failing because of a bug in grunt-link-checker. I've already made a PR (https://github.com/ChrisWren/grunt-link-checker/pull/32) but I'm not sure if this is still maintained or not
- I tried to replace it with grunt-spider, which is another plugin to test for missing links but that one also has a bug and a much harder to solve
- in the meanwhile I've forked the grunt-link-checker and applied the patch. 3DR can do the same or you can link to my repo. I've sent PR #276 for this

**Comment by hamishwillee** [comment]
@OXINARF Thanks very much for your advice on this. I'm not familiar enough with the test system to judge this patch, so I'll handball to someone else in the team.

**Comment by mrpollo** [comment]
Thanks @OXINARF, I'll fork `grunt-lint-checker` and merge your commits (pending review), this should hopefully fix this situation!

**Comment by hamishwillee** [comment]
@mrpollo Thanks. I'm also about to do some minor updates to this PR too.

**Comment by mrpollo** [comment]
@OXINARF perhaps we should discuss this on a new issue, @hamishwillee where would the best place be?

**Comment by hamishwillee** [comment]
@mrpollo There isn't an existing place - just create one in this repo.

**Comment by hamishwillee** [comment]
@mrpollo @peterbarker Once the test error is fixed, this is ready to merge (please). UPdated section with (excellent) advice from @timlee3dr

**Pull request merged**
