### PR TITLE
Wrong link, try to fix tests

### LINKED ISSUE #263: travis reports wrong links in /advanced-logs.html
we need to find why travis thinks this is wrong
```
[Tue, 26 Jan 2016 08:16:05 GMT] "GET /advanced-logs.html#downloading-using-scp-mac-linux" "Node/simplecrawler 0.4.2 (git+ssh://git@github.com/cgiffard/node-simplecrawler.git)"
>> Error finding content with the following fragment identifier linked from http://localhost:4000/advanced-logs.html to http://localhost:4000/advanced-logs.html#downloading-using-scp-mac-linux
```

### PR DESCRIPTION
**Pull request by OXINARF**
Fixes #263

### CODE REVIEW

**Comment by OXINARF** [comment]
Looking at Travis/Circle logs, it is clear that the link is created at *downloading-using-scp-maclinux*, but in production it seems it is *downloading-using-scp-mac-linux*, so there should be something different in production.

**Comment by hamishwillee** [comment]
@OXINARF I don't like this fix. Yes the tests might pass, but now the actual link on production fails - ie the original link http://dev.3dr.com/advanced-logs.html#downloading-using-scp-mac-linux works but the fix does not (http://dev.3dr.com/advanced-logs.html#downloading-using-scp-maclinux).

Thoughts?

**Comment by mrpollo** [comment]
Thanks for the path @OXINARF, I'm afraid as @hamishwillee says we can't accept it, we need to get to the bottom of this dev vs prod situation.

Can you help us by sharing details from your local environment?, and if tests pass there

**Comment by OXINARF** [comment]
@hamishwillee Yes, I noticed that production was different after making the PR, that's why I made the second comment. This is clearly a difference in test environment and the production environment: I can only thing of two things, either a different gitbook version or different OS?

@mrpollo I haven't made the test locally, I saw the logs, noticed the actual link that the tests were generating and made the PR. After that I noticed the production actually generated a different link. I'll try to look for the generation of the links to understand why in production it replaces */* with a *-* and in tests it doesn't.

**Comment by OXINARF** [comment]
@mrpollo Ok, I have tracked it down the generation of ids (https://github.com/GitbookIO/gitbook/commit/df1d5a06802154c5b6fb922c73365d2afceaecd9). It seems like it should work because the piece that generates it (github-slugid) only has one version. Maybe the RegEx is working differently in the production for some weird reason?

Anyway I made a commit that uses a custom id that should work both in tests and in production. Although it is a hack (in the way that it doesn't solve the different environment) I think it should be accepted to at least solve the problem that no test ever passes.

**Comment by hamishwillee** [comment]
@OXINARF Thanks! I agree this should be accepted - though would be good to find out the different in environments still.

Just for my information, where did you find the syntax - I couldn't find it anywhere?

**Comment by OXINARF** [comment]
@hamishwillee in the commit I linked you can see they added a test where they have a custom id. That's the only place I found it too.

**Comment by hamishwillee** [comment]
Well done for finding it. An elegant workaround :-)

**Pull request merged**
