### PR TITLE
Fixes #202

### LINKED ISSUE #202: Instructions for importing logs
**Author:** Nick
**Page:** http://dev.3dr.com/starting-troubleshooting.html

Could you please add to this page to make it more friendly to new-ish users? Right now in the app you can email logs to yourself, but this functionality is going away in the next version of the app (they go directly to zendesk) so I'd like to be able to direct people to this page if they want to pull their own logs.

I think it just needs these instructions, formatted better:

mkdir solo controller
scp root@10.1.1.1:/log/* ./controller
TjSDBkAu
scp root@10.1.1.10:/log/ ./solo
TjSDBkAu

### PR DESCRIPTION
**Pull request by hamishwillee**
This fixes #202 - essentially it documents how to use the feature in solo cli document and links to this from the Troubleshooting topic.

@tcr3dr Most of the detailed information about logging is actually not all that appropriate/useful in "Troubleshooting".  
I propose that we move this content into its own page in "Advanced Topics" under page title "System Logs". We still need information about logs in Troubleshooting but this can just be  the existing heading and the new link to the solo cli. Instead of all the detail we have one line saying something like "System logs can help debug problems with Solo and the Controller." (and that mention of System logs can go to the detail page we just created. Make sense?

### CODE REVIEW

**Comment by mrpollo** [comment]
@tcr3dr should we include the new cli factory reset? `solo flash both factory`?

**Comment by tcr3dr** [comment]
`solo flash both factory --clean`

**Comment by hamishwillee** [comment]
> solo flash both factory --clean

@tcr3dr @mrpollo Is this an action for me? If so, what?

**Comment by hamishwillee** [comment]
@tcr3dr @mrpollo Can I get this reviewed and merged? We've got an outstanding request from @nick3dr for improvements in this area!

I have just updated this so that it splits out a topic for System Logs (out of troubleshooting - now linked from there). This explains how to download logs as both a developer (using solo cli) and as a user (SCP/WinSCP). I was hesitant to try to add non-developer content to support Nick's end user goals, but I think it isn't disruptive, and some developers will actually prefer this approach. 

The page also extends the information on log types based on information from #224. It is not exhaustive, but it is a hell of a lot more useful than previously.

**Comment by mrpollo** [comment]
failing tests!, I just verified this is due to problems with your PR, can you verify plz?

**Comment by hamishwillee** [comment]
@mrpollo The only reported test fail AFAIK is to this link: http://localhost:4000/advanced-logs.html#downloading-using-scp-mac-linux - is that what you see?

But ... when rebuild and test that link it works perfectly. So I think the test is broken.

Suggest we merge.

**Comment by mrpollo** [comment]
tests are broken, but unrelated to this branch, I'm going to pull this into master and then provide a new PR to fix the tests

**Comment by hamishwillee** [comment]
@mrpollo The docs for the examples also look different, and the local build no longer displays a sidebar.

**Comment by hamishwillee** [comment]
I think the css files for those got trashed.

**Comment by mrpollo** [comment]
master looks like trash?

**Comment by hamishwillee** [comment]
Not quite. So see sidebar on live site http://dev.3dr.com/example-dronekit.html. It displays (great) but the software examples Tim added are now gone.

On my local copy (just synced from master) the sidebar does not render at all. It did render before I pulled master.

Does that answer?

**Comment by hamishwillee** [comment]
But I'm very happy to have the docs I put in updated :-)

**Comment by mrpollo** [comment]
Let me check, can you open a new issue for this?

**Comment by hamishwillee** [comment]
Sure. #237 and #238

**Pull request merged**
