### PR TITLE
Update hardware-accessorybay.md

### PR DESCRIPTION
**Pull request by hamishwillee**
Update accessory pinout table with information as provided by TimLee here: https://discuss.dronekit.io/t/peripherals-mapping-between-accessory-port-pixhawk2-and-arducopter-parameters-to-connect-secondary-rtk-gps/198/4

### CODE REVIEW

**Comment by hamishwillee** [comment]
@timlee3dr Hi Tim
1. Can you confirm that this PR accurately reflects the information you provided? 
2. There were no descriptions for USB GND and BUS ID pins - is there anything we can say for those?
3. The pin `SER5 RX (DEBUG) | UART5 RX input to Pixhawk 2.`. Does this mean that SER5 RX is explicitly reserved for debug information? Would it be better to write`SER5 RX | UART5 RX input to Pixhawk 2. Used as a debug port.` Is there a debug protocol or other information on debugging that we can link to (ie if someone wants to use this port for debugging, where do they go for next steps?)

**Comment by hamishwillee** [comment]
@mrpollo There is something wrong with CI in this one. Checks are failing in pages I didn't touch.

**Comment by hamishwillee** [comment]
@mrpollo Can you please merge this change. The failures are something to do with #251 - not the content here.

**Comment by mrpollo** [comment]
thanks guys

**Comment by hamishwillee** [comment]
@mrpollo Thanks very much. This is not live on the site though - ETA?

**Pull request merged**
