### PR TITLE
Add additional options for installing Solo-cli

### PR DESCRIPTION
**Pull request by hamishwillee**
This addresses #245 by providing alternative instructions to uninstalling/installing/upgrading solo-cli on Linux.

### CODE REVIEW

**Comment by mrpollo** [comment]
can you change the pip package install instructions?, This should be the preferred way of installing:

```
sudo -H pip install X
```
Upgrades should be:
```
sudo -H pip install X --upgrade
```

Installing/Upgrading DroneKit-SITL should be:

```
# installing
sudo -H pip install dronekit-sitl
# upgrading
sudo -H pip install dronekit-sitl --upgrade
```

**Comment by hamishwillee** [comment]
@mrpollo Changed. Does this now do what you want?

**Comment by mrpollo** [comment]
what do you think of mixing `git+https://github.com/3drobotics/solo-cli` and `solo-cli` for `pip install`?

**Comment by hamishwillee** [comment]
> what do you think of mixing git+https://github.com/3drobotics/solo-cli and solo-cli for pip install?

You can't do `pip install solo-cli` because it isn't hosted on pypi, but you can do `pip uninstall solo-cli`

Basically I don't know what you mean/or are suggesting here?

**Comment by mrpollo** [comment]
@hamishwillee I updated the PR with latest from master, also updated the upgrading solo-cli to what I was trying to explain, this i believe is what we should ship, what do you think?

**Comment by hamishwillee** [comment]
OK, I get it now. They are not quite the same things - what you have provided is "how to upgrade" using the bog standard method. 
I'd covered that method in the text ("just add --upgrade to above line") and then a completely new approach if that fails: ``sudo pip install https://github.com/3drobotics/solo-cli/archive/master.zip --no-cache-dir``

Sounds like you don't think this information is useful? That's OK, but then the wording needs to change a little. I've done that now so you can merge.

**Comment by peterbarker** [comment]
LGTM.

**Pull request merged**
