### PR TITLE
examples/webserver: remove use of greenlets

### LINKED ISSUE #287: Running webserver example on Solo gives ERROR LOADING MAVNATIVE
Running server.py on Solo gives the following error:

...
running script...

ERROR LOADING MAVNATIVE - falling back to python implementation
Connecting to udpin:0.0.0.0:14550...
Traceback (most recent call last):
  File "/log/solo-script/server.py", line 43, in <module>
    eventlet.spawn(latlog, vehicle)
AttributeError: 'module' object has no attribute 'spawn'
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/log/solo-script/env/lib/python2.7/site-packages/dronekit/mavlink.py", line 89, in mavlink_thread_out
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/log/solo-script/env/lib/python2.7/site-packages/dronekit/mavlink.py", line 124, in mavlink_thread_in
  File "/log/solo-script/env/lib/python2.7/site-packages/dronekit/__init__.py", line 1244, in listener
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'time'

while running it locally works nicely.

### PR DESCRIPTION
**Pull request by peterbarker**
Fixes #287

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @peterbarker 

1. This seems to remove "eventlet" not "greenlet" as per the title

2. I still see this error in the log when installing to Solo: ``cp: can't stat '/usr/lib/python2.7/site-packages/greenlet*': No such file or directory``

3. Running this on Solo gives me this error:
```
D:\Github\solodevguide\examples\webserver>solo script run server.py
connecting to solo...
checking pip...
uploading script bundle...
./
./requirements.txt
./server.py
./static/
./static/jquery.min.js
./static/socket.io.min.js
./templates/
./templates/index.html
Not deleting env/bin
New python executable in env/bin/python
Installing setuptools, pip, wheel...done.
cp: can't stat '/usr/lib/python2.7/site-packages/greenlet*': No such file or directory
Ignoring indexes: https://pypi.python.org/simple
Requirement './wheelhouse/*.whl' looks like a filename, but the file does not exist
*.whl is not a valid wheel filename.
running script...

Traceback (most recent call last):
  File "/log/solo-script/server.py", line 1, in <module>
    from flask import Flask, render_template
ImportError: No module named flask
```
4. Also need to update **/book/example-webserver.md** to remove the mention of eventlet.

Does this have any other "implications"? Ie why was greenlets used in the first place?

**Comment by peterbarker** [comment]
greenlets were backing the eventlets.

The "cp" of the greenlet files should go away once we verify no other example is using it.  Or possibly juts right now.

Your "pack" appears to be missing every wheel, not just flask.  Can you present the listing of files in solo-sript.tar.gz, please?

I do not know why someone went to the trouble of using greenlets - the "cp" hack shows it was not a natural thing to do.  They will probably have better performance than standard threading, but they do have the disadvantage of... not working on Solo ATM.

**Comment by hamishwillee** [comment]
I've sent you the tar. You're right - wheels are missing.

**Comment by hamishwillee** [comment]
The tar issue fixed by https://github.com/3drobotics/solo-cli/pull/40

@peterbarker 

Example runs and install. Two issues to fix before can merge (that I will leave with you):
1. Docs suggest connect on http://10.1.1.10:5000/ . Change URL to  http://10.1.1.10:8080/
2. Example completes with:
   ```
   * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
   ```
   Would be better if it said:
   ```
   * Connect to on http://10.1.1.10:8080/ on your browser (Press CTRL+C to quit)
   ```

FYI, I suspect the reason they went greenlets would be this note int he output: 
```
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
```

**Comment by peterbarker** [comment]
```   * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)```

Will patch the docs.

**Comment by franknitty69** [comment]
I was running the Webserver example and received the errors that this pr looks to fix. I was just curious if it will be merged.

**Comment by mrpollo** [comment]
thanks @peterbarker

**Pull request merged**
