### PR TITLE
Added VLC screenshot

### PR DESCRIPTION
**Pull request by franknitty69**
Added screenshot of VLC showing Viewing Live Video working in the Video Pipeline section.

### CODE REVIEW

**Comment by mrpollo** [comment]
thanks for the contribution!, would you mind squashing your commits into 1?, other than that this looks good, pending @hamishwillee approval

**Comment by franknitty69** [comment]
can i squash commits in an open pull request? or do i need to close the PR, squash and then submit another PR?

**Comment by mrpollo** [comment]
Any changes to the branch will remain under this PR while its open, no need
to close and open a new one.
On Mon, Dec 14, 2015 at 4:01 PM Ahmed Agbabiaka <notifications@github.com>
wrote:

> can i squash commits in an open pull request? or do i need to close the
> PR, squash and then submit another PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3drobotics/solodevguide/pull/230#issuecomment-164599218>
> .
>
-- 
◤RAMÓN ROCHE
    SENIOR SOFTWARE ENGINEER
    3D Robotics
    415.599.1404
    website <http://www.3dr.com/> | facebook
<http://www.facebook.com/3drobotics> | instagram
<http://www.instagram.com/3drobotics>

**Comment by franknitty69** [comment]
i'm not sure why local squash keeps pulling in all these other commits.

git rebase -i HEAD~7 *last 7 commits
set 2-6 to squash
git push origin master --force

i'm not sure what i'm doing wrong. maybe i should close the pr and start over :(

**Comment by franknitty69** [comment]
i think i finally got it right. :+1:

**Comment by mrpollo** [comment]
looks good man thanks for the help.

@hamishwillee please check this on a local build so you can check the image dimensions against it?, if you think this is a good change you can merge.

**Comment by mrpollo** [comment]
Also tests fail due to un-related issue.

**Comment by mrpollo** [comment]
thanks again @franknitty69

**Pull request merged**
